# docker-compose.yml

services:
  postgres:
    image: postgres:17
    container_name: pg-fastapi
    environment:
      POSTGRES_DB: techzen_academy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: codegym
      TZ: Asia/Ho_Chi_Minh
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d techzen_academy" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - backend_net

volumes:
  pgdata:

networks:
  backend_net:
    name: techzen_backend_net
    driver: bridge